### PR TITLE
Clean up tests

### PR DESCRIPTION
**Pull request by thoov**
- Use function over arrow functions
- Cleaned up an incorrect module name
- Renamed enumberble to enumberable
- Added back depercation check

### CODE REVIEW

**Comment by rwjblue** [comment]
> Use arrow functions

🤔 , I don't think we should be using arrow functions with QUnit generally speaking.  You loose access to the test environment (`this` context inside the tests), which is required in general for Ember app testing...

**Comment by rwjblue** [comment]
https://github.com/platinumazure/eslint-plugin-qunit/blob/master/docs/rules/no-arrow-tests.md has a better writeup I believe...

**Comment by thoov** [comment]
@rwjblue Ya I guess I will go the other way. I kept the tests that access this to use function but having them split is probably more trolly

**Comment by thoov** [comment]
@rwjblue Updated

**Comment by thoov** [comment]
Oops forgot that folder

**Pull request merged**
