### PR TITLE
Add Ember.String.fmt support

### PR DESCRIPTION
**Pull request by locks**
Includes String.prototype.fmt.

### CODE REVIEW

**Comment by thoov** [comment]
@locks Can you migrate the tests you removed from https://github.com/emberjs/ember.js/pull/15882/files#diff-a0ba8b55a58c5bceb155533f54dca369 over to here?

**Comment by locks** [comment]
Working on it :) Not sure how to get `ENV.EXTEND_PROTOTYPES.String`, though.

**Comment by thoov** [comment]
@locks If you remove ember-disable-prototype-extensions then they will start working correctly

**Comment by thoov** [comment]
And you can grab them from EmberENV.EXTEND_PROTOTYPES.String

**Comment by locks** [comment]
Thank you @thoov for spotting some silly mistakes on my initial code.

**Comment by thoov** [comment]
@locks thanks!

**Comment by thoov** [comment]
This closes #1

**Pull request merged**
