### PR TITLE
Add deprecated `registry` property to Application/ApplicationInstance

### PR DESCRIPTION
**Pull request by cibernox**
Removal in https://github.com/emberjs/ember.js/pull/15912

### CODE REVIEW

**Comment by thoov** [comment]
@cibernox Move the test that you removed from https://github.com/emberjs/ember.js/pull/15912/files#diff-7ed395980aff799efa70007547a47210 into this?

**Comment by rwjblue** [comment]
Also needs a rebase

**Comment by rwjblue** [comment]
@cibernox  - Ping?

**Comment by cibernox** [comment]
I somehow missed notifications about this. Done.

**Comment by rwjblue** [comment]
👍

**Pull request merged**
